defaults: &defaults
  fog_provider: 'AWS'
  aws_access_key_id: 'AKIAJ5NVMZUQFLGQDSVA'
  aws_secret_access_key: 'EEFxOfzxIDlsX1LrkGW0FQRQqAmQbvvx878NZh4T'
  fog_directory: 'gradnyc'
  # You may need to specify what region your storage bucket is in
  # fog_region: "eu-west-1"
  existing_remote_files: delete
  # To delete existing remote files.
  # existing_remote_files: delete 
  # Automatically replace files with their equivalent gzip compressed version
  gzip_compression: true
  # Fail silently.  Useful for environments such as Heroku
  # fail_silently = true
  enabled: true

development:
  <<: *defaults
  enabled: false

test:
  <<: *defaults

stage:
  <<: *defaults
  fog_directory: 'gradnyc-stage'

production:
  <<: *defaults
